{% set name = "gcsfs" %}
{% set version = "2021.8.1" %}
{% set sha256 = "93822b5cfec4f374091cfdf95133f0a51c3970c9d08f3bd6599897ad7c000f78" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - google-auth >=1.2
    - google-auth-oauthlib
    - requests
    - decorator
    - fsspec ==2021.08.1
    - aiohttp

test:
  imports:
    - gcsfs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dask/gcsfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pythonic file-system interface for Google Cloud Storage
  doc_url: http://gcsfs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - jcrist
    - tomaugspurger
