{% set name = "gcsfs" %}
{% set version = "2024.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gcsfs-{{ version }}.tar.gz
  sha256: e672413922108300ebc1fe78b8f99f3c7c1b94e7e088f5a6dc88de6d5a93d156

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # https://github.com/fsspec/gcsfs/blob/2024.12.0/setup.py#L23
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip

  run:
    - python
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - decorator >4.1.2
    # Must be the same version of gcsfs
    - fsspec ==2024.12.0
    - google-auth >=1.2
    - google-auth-oauthlib
    - google-cloud-storage
    - requests

test:
  source_files:
    - gcsfs
  imports:
    - gcsfs
  commands:
    - pip check
    - pytest -v gcsfs/tests
  requires:
    - pip

about:
  home: https://github.com/dask/gcsfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Pythonic file-system interface for Google Cloud Storage
  doc_url: http://gcsfs.readthedocs.io/en/latest/
  dev_url: https://github.com/fsspec/gcsfs
  description: A pythonic file-system interface to Google Cloud Storage.

extra:
  recipe-maintainers:
    - martindurant
    - jcrist
    - tomaugspurger
