{% set name = "gcsfs" %}
{% set version = "2022.11.0" %}
{% set sha256 = "84d0caada7097e357d735d7e16e8064f0819d28746101d6f65ff42938557e831" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # temporarily disable py312 until fsspec is rebuilt
  skip: True  # [py>311]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools

  run:
    - python
    - google-auth >=1.2
    - google-auth-oauthlib
    - google-cloud-storage >1.40
    - requests
    - decorator >4.1.2
    - fsspec =={{ version }}
    - aiohttp

test:
  imports:
    - gcsfs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dask/gcsfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD-3-Clause
  summary: Pythonic file-system interface for Google Cloud Storage
  description: |
    This package depends on fsspec, and inherits many useful behaviours from there, including integration with Dask,
    and the facility for key-value dict-like objects of the type used by zarr.
  doc_url: http://gcsfs.readthedocs.io
  dev_url: https://github.com/fsspec/gcsfs

extra:
  recipe-maintainers:
    - martindurant
    - jcrist
    - tomaugspurger
