{% set name = "gcsfs" %}
{% set version = "2025.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a9c1c32b7899a3967ba30a7e9422cdfda596266f03476cdf5545402b8af4cd5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - decorator >4.1.2
    - fsspec =={{ version }}
    - google-auth >=1.2
    - google-auth-oauthlib
    - google-cloud-storage
    - google-cloud-storage-control
    - requests

# Ignore tests which trying to use docker
#   > raise CalledProcessError(retcode, process.args, output=stdout, stderr=stderr)
#   E subprocess.CalledProcessError: Command '['docker', 'ps', '-a', '-q', '--filter', 'name=gcsfs_test']' returned non-zero exit status 1.
{% set ignore_tests = " --ignore=gcsfs/tests/test_core.py" %}
{% set ignore_tests = ignore_tests + " --ignore=gcsfs/tests/derived" %}
{% set deselect_tests = " --deselect=gcsfs/tests/test_inventory_report_listing.py::test_ls_base" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_mapping.py::test_map_simple" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_mapping.py::test_map_default_gcsfilesystem" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_mapping.py::test_map_errors" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_mapping.py::test_map_with_data" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_mapping.py::test_map_clear_empty" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_mapping.py::test_map_pickle" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_mapping.py::test_map_array" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_mapping.py::test_map_bytearray" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_mapping.py::test_new_bucket" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_mapping.py::test_api" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_retry.py::test_metadata_read_permissions" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_checkers.py::test_validate_headers" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_checkers.py::test_checker_validate_http_response" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_checkers.py::test_checker_validate_json_response" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_core_versioned.py::test_info_versioned" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_core_versioned.py::test_cat_versioned" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_core_versioned.py::test_cp_versioned" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_core_versioned.py::test_ls_versioned" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_core_versioned.py::test_find_versioned" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_credentials.py::test_googlecredentials_none" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_credentials.py::test_credentials_from_raw_token" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_init.py::TestConditionalImport::test_experimental_env_unset" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_init.py::TestConditionalImport::test_experimental_env_set" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_inventory_report.py::TestInventoryReport::test_validate_inventory_report_info" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_inventory_report.py::TestInventoryReport::test_fetch_raw_inventory_report_config" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_inventory_report.py::TestInventoryReport::test_fetch_inventory_report_metadata" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_inventory_report.py::TestInventoryReport::test_sort_inventory_report_metadata" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_inventory_report.py::TestInventoryReport::test_download_inventory_report_content" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_inventory_report.py::TestInventoryReport::test_parse_inventory_report_line" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_inventory_report.py::TestInventoryReport::test_parse_inventory_reports" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_inventory_report.py::TestInventoryReport::test_construct_final_snapshot" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_inventory_report.py::TestInventoryReport::test_parse_raw_inventory_report_config_invalid_date" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_inventory_report.py::TestInventoryReport::test_parse_raw_inventory_report_config_missing_metadata_fields" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_inventory_report.py::TestInventoryReport::test_parse_raw_inventory_report_config_returns_correct_config" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_inventory_report.py::TestInventoryReportConfig::test_inventory_report_config_creation" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_retry.py::test_tempfile" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_retry.py::test_retriable_exception" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_retry.py::test_pickle_serialization" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_retry.py::test_multiprocessing_error_handling" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_retry.py::test_validate_response" %}
{% set deselect_tests = deselect_tests + " --deselect=gcsfs/tests/test_zb_hns_utils.py::test_download_range" %}

test:
  source_files:
    - gcsfs
  imports:
    - gcsfs
    - gcsfs.checkers
    - gcsfs.core
    - gcsfs.credentials
    - gcsfs.inventory_report
    - gcsfs.retry
  commands:
    - pip check
    # Unable to use the "pyargs", tests are not in the site-packages directory.
    - pytest -v gcsfs/tests --asyncio-mode=auto {{ ignore_tests }} {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - pytest-asyncio

about:
  home: https://github.com/dask/gcsfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Pythonic file-system interface for Google Cloud Storage
  doc_url: https://gcsfs.readthedocs.io
  dev_url: https://github.com/fsspec/gcsfs
  description: A pythonic file-system interface to Google Cloud Storage.

extra:
  recipe-maintainers:
    - martindurant
    - jcrist
    - tomaugspurger
