{% set name = "gcsfs" %}
{% set version = "0.7.1" %}
{% set sha256 = "03658dfbf1a734d987aab3631e0a342b3d7e24a24998b4d8d2491fdd21053720" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - google-auth
    - google-auth-oauthlib
    - requests
    - fsspec >=0.8.0
    - aiohttp

test:
  imports:
    - gcsfs

about:
  home: https://github.com/dask/gcsfs
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Pythonic file-system interface for Google Cloud Storage
  doc_url: http://gcsfs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - jcrist
    - tomaugspurger
