{% set name = "gcsfs" %}
{% set version = "2021.4.0" %}
{% set sha256 = "8503b59d7afc98fdddbba67a615010982cf1c737d5c481d67235a47a5fcc043f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - google-auth >=1.2
    - google-auth-oauthlib
    - requests
    - decorator
    - fsspec ==2012.04.0
    - aiohttp

test:
  imports:
    - gcsfs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dask/gcsfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pythonic file-system interface for Google Cloud Storage
  doc_url: http://gcsfs.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - martindurant
    - jcrist
    - tomaugspurger
