{% set name = "gcsfs" %}
{% set version = "2026.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fsspec/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 06f99b24177d51af3338d495fd6c4ea0f7dc1ff80782d36d6e5c6bae88bbe2c5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - hatchling >=1.27.0
    - hatch-vcs
  run:
    - python
    - aiohttp >=3.9.0,!=4.0.0a0,!=4.0.0a1
    - decorator >4.1.2
    - fsspec >=2026.3.0,!=2026.4.0
    - google-auth >=1.2
    - google-auth-oauthlib
    - google-cloud-storage >=3.9.0
    - google-cloud-storage-control
    - requests

# as of 2026.5.0, all relevant tests to use docker
#   > raise CalledProcessError(retcode, process.args, output=stdout, stderr=stderr)
#   E subprocess.CalledProcessError: Command '['docker', 'ps', '-a', '-q', '--filter', 'name=gcsfs_test']' returned non-zero exit status 1.

test:
  imports:
    - gcsfs
    - gcsfs.checkers
    - gcsfs.core
    - gcsfs.credentials
    - gcsfs.inventory_report
    - gcsfs.retry
  commands:
    - pip check
    # since 2026.5.0 relevant upstream tests all use docker. skip.
  requires:
    - pip
    - pytest
    - pytest-asyncio

about:
  home: https://github.com/dask/gcsfs
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Pythonic file-system interface for Google Cloud Storage
  doc_url: https://gcsfs.readthedocs.io
  dev_url: https://github.com/fsspec/gcsfs
  description: A pythonic file-system interface to Google Cloud Storage.

extra:
  recipe-maintainers:
    - martindurant
    - jcrist
    - tomaugspurger
