travis:
  secure:
    BINSTAR_TOKEN: UY5YwtOrd0nuhoWXKpBOY1GzCVvdeM34qSbI+24kCs/v4c6Ok9QkOiVwGoOt0lN/9hnY+lVK1hGWibHcUkCav4mhqDL3TK3RGlbMEfcCDvkhdIJ56mWOzobygZAM5fGiElWV3x+j7mEDHWn/iBuwQ44O+qDrlFYCb9YcCi7hJW+oq7qbU+ARp48Urnyow7QXIljtSiOfTpf1vPqLwc/WWgoIbfJRsNeTEaGwZNV2rn/mGx+miX1+mj894v301UPyaAnj6iKz/Ff4N+kGDdEYQvSq7jmmsLqJJCTtc/QeJid5FiGesh2qNRSp5UxeflW9sQLtUPpy/9bM0Hd0gep0irFa5LW1xgYMHQdF2fC3p4zi+8F5tAfshFWmT/zArRM1uhQEnt8mI2w6aqgbPhK9Jhvk0Vft+jdyr32zXY6X7AiRAO108GNrGj2vpLty69G5dhYazwn6Rj6oZIi+PpEA4jPHHoEx86MZxH4vTm3JjGYCWyEq2kifcF/Ek+B8iq9KQrHMUcb4prav9muDA20Z9FMSU4csxHWdqH3ZNhsOtSDWo1kUNh45Y3V2YO+wv4VgPgL85sXnKJ+YVTBG1bzK6Mkhhxyls5OU6/J5lIM57AB3N00XJoiYjyiSMju/87VuwkxJn0Da56E0HtAGwveQA/GyzDaZXAHZmBc3rhBbml0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
