travis:
  secure:
    BINSTAR_TOKEN: uxXGOG7NYZ9oFHaaW/ZPqJOpg1elZX6AYEAEpq93cX3PjK/j32jmlqG2um+UB7L0xfkRO3P1mvtnBvRfXlbPAEc93rozkbN8kdo70+Qdeszh+IIFJEq26cmxg1gqpf6ZYOVVXcS8SzEAURrekvqqsjAiELqfuiHUvpfrcqoJjkLMQe5oClNoxCLzlTuu3QLByaqj9ATagdf2uXg0tXcijuDyzSUAgQT7TaLPaRivBzTlti2NOHvVHNGGq3YaBn5tvYSHtlWJq+mTCUpdABtxJc6GrIOI5yfsWyUNE9M0q7jLF239vwRv91p+K/pNW2QdeM33nb1SQVLPldnXb/S6kYHblHw99c4lV5GrPC1/txVdjZigMfTpj6ZAH4m4WQ3OMYPGS1pz2f5MseQh+DkDmRcpokAY628nll/thTCI/WSaF+cWVkzeRcDsnlhDQNmV9tPVhJyfbWxjlotpn77rqViDvERQ/LoxukFlNoP6cV9LmWQ+dbY5rTDt98jshOrmWlaF/jgnd7bb9FLsFVcogSvNCWl6ddr+VWPvR9aHnIiZJ5FG1eTLw0//HtsMlEqTy8yaXy6o1aloaRPYZ8GF/DHCFLCD3ejdBeqTCbc1sXCmsnjv2vijmIBo9rT5NSQ2rFcuIb7YzJjJhrIwFfTjjB/8lObI3JNkdVlV5SoVlNE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
